package travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * Agents generated by hbm2java
 */
public class Agents implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer agentId;
	private String agtFirstName;
	private String agtMiddleInitial;
	private String agtLastName;
	private String agtBusPhone;
	private String agtEmail;
	private String agtPosition;
	private Integer agencyId;

	public Agents() {
	}

	public Agents(String agtFirstName, String agtMiddleInitial, String agtLastName, String agtBusPhone, String agtEmail,
			String agtPosition, Integer agencyId) {
		this.agtFirstName = agtFirstName;
		this.agtMiddleInitial = agtMiddleInitial;
		this.agtLastName = agtLastName;
		this.agtBusPhone = agtBusPhone;
		this.agtEmail = agtEmail;
		this.agtPosition = agtPosition;
		this.agencyId = agencyId;
	}

	public Integer getAgentId() {
		return this.agentId;
	}

	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}

	public String getAgtFirstName() {
		return this.agtFirstName;
	}

	public void setAgtFirstName(String agtFirstName) {
		this.agtFirstName = agtFirstName;
	}

	public String getAgtMiddleInitial() {
		return this.agtMiddleInitial;
	}

	public void setAgtMiddleInitial(String agtMiddleInitial) {
		this.agtMiddleInitial = agtMiddleInitial;
	}

	public String getAgtLastName() {
		return this.agtLastName;
	}

	public void setAgtLastName(String agtLastName) {
		this.agtLastName = agtLastName;
	}

	public String getAgtBusPhone() {
		return this.agtBusPhone;
	}

	public void setAgtBusPhone(String agtBusPhone) {
		this.agtBusPhone = agtBusPhone;
	}

	public String getAgtEmail() {
		return this.agtEmail;
	}

	public void setAgtEmail(String agtEmail) {
		this.agtEmail = agtEmail;
	}

	public String getAgtPosition() {
		return this.agtPosition;
	}

	public void setAgtPosition(String agtPosition) {
		this.agtPosition = agtPosition;
	}

	public Integer getAgencyId() {
		return this.agencyId;
	}

	public void setAgencyId(Integer agencyId) {
		this.agencyId = agencyId;
	}

}
