package travelexperts;
// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * Bookings generated by hbm2java
 */
public class Bookings implements java.io.Serializable {

	private Integer bookingId;
	private Date bookingDate;
	private String bookingNo;
	private Double travelerCount;
	private Integer customerId;
	private String tripTypeId;
	private Integer packageId;

	public Bookings() {
	}

	public Bookings(Date bookingDate, String bookingNo, Double travelerCount, Integer customerId, String tripTypeId,
			Integer packageId) {
		this.bookingDate = bookingDate;
		this.bookingNo = bookingNo;
		this.travelerCount = travelerCount;
		this.customerId = customerId;
		this.tripTypeId = tripTypeId;
		this.packageId = packageId;
	}

	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	public String getBookingNo() {
		return this.bookingNo;
	}

	public void setBookingNo(String bookingNo) {
		this.bookingNo = bookingNo;
	}

	public Double getTravelerCount() {
		return this.travelerCount;
	}

	public void setTravelerCount(Double travelerCount) {
		this.travelerCount = travelerCount;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getTripTypeId() {
		return this.tripTypeId;
	}

	public void setTripTypeId(String tripTypeId) {
		this.tripTypeId = tripTypeId;
	}

	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

}
