package travelexperts;
// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {

	private EmployeesId id;

	public Employees() {
	}

	public Employees(EmployeesId id) {
		this.id = id;
	}

	public EmployeesId getId() {
		return this.id;
	}

	public void setId(EmployeesId id) {
		this.id = id;
	}

}
