package travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * PackagesProductsSuppliersId generated by hbm2java
 */
public class PackagesProductsSuppliersId implements java.io.Serializable {

	private int packageId;
	private int productSupplierId;

	public PackagesProductsSuppliersId() {
	}

	public PackagesProductsSuppliersId(int packageId, int productSupplierId) {
		this.packageId = packageId;
		this.productSupplierId = productSupplierId;
	}

	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	public int getProductSupplierId() {
		return this.productSupplierId;
	}

	public void setProductSupplierId(int productSupplierId) {
		this.productSupplierId = productSupplierId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PackagesProductsSuppliersId))
			return false;
		PackagesProductsSuppliersId castOther = (PackagesProductsSuppliersId) other;

		return (this.getPackageId() == castOther.getPackageId())
				&& (this.getProductSupplierId() == castOther.getProductSupplierId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPackageId();
		result = 37 * result + this.getProductSupplierId();
		return result;
	}

}
