package travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * Suppliercontacts generated by hbm2java
 */
public class Suppliercontacts implements java.io.Serializable {

	private int supplierContactId;
	private String supConFirstName;
	private String supConLastName;
	private String supConCompany;
	private String supConAddress;
	private String supConCity;
	private String supConProv;
	private String supConPostal;
	private String supConCountry;
	private String supConBusPhone;
	private String supConFax;
	private String supConEmail;
	private String supConUrl;
	private String affiliationId;
	private Integer supplierId;

	public Suppliercontacts() {
	}

	public Suppliercontacts(int supplierContactId) {
		this.supplierContactId = supplierContactId;
	}

	public Suppliercontacts(int supplierContactId, String supConFirstName, String supConLastName, String supConCompany,
			String supConAddress, String supConCity, String supConProv, String supConPostal, String supConCountry,
			String supConBusPhone, String supConFax, String supConEmail, String supConUrl, String affiliationId,
			Integer supplierId) {
		this.supplierContactId = supplierContactId;
		this.supConFirstName = supConFirstName;
		this.supConLastName = supConLastName;
		this.supConCompany = supConCompany;
		this.supConAddress = supConAddress;
		this.supConCity = supConCity;
		this.supConProv = supConProv;
		this.supConPostal = supConPostal;
		this.supConCountry = supConCountry;
		this.supConBusPhone = supConBusPhone;
		this.supConFax = supConFax;
		this.supConEmail = supConEmail;
		this.supConUrl = supConUrl;
		this.affiliationId = affiliationId;
		this.supplierId = supplierId;
	}

	public int getSupplierContactId() {
		return this.supplierContactId;
	}

	public void setSupplierContactId(int supplierContactId) {
		this.supplierContactId = supplierContactId;
	}

	public String getSupConFirstName() {
		return this.supConFirstName;
	}

	public void setSupConFirstName(String supConFirstName) {
		this.supConFirstName = supConFirstName;
	}

	public String getSupConLastName() {
		return this.supConLastName;
	}

	public void setSupConLastName(String supConLastName) {
		this.supConLastName = supConLastName;
	}

	public String getSupConCompany() {
		return this.supConCompany;
	}

	public void setSupConCompany(String supConCompany) {
		this.supConCompany = supConCompany;
	}

	public String getSupConAddress() {
		return this.supConAddress;
	}

	public void setSupConAddress(String supConAddress) {
		this.supConAddress = supConAddress;
	}

	public String getSupConCity() {
		return this.supConCity;
	}

	public void setSupConCity(String supConCity) {
		this.supConCity = supConCity;
	}

	public String getSupConProv() {
		return this.supConProv;
	}

	public void setSupConProv(String supConProv) {
		this.supConProv = supConProv;
	}

	public String getSupConPostal() {
		return this.supConPostal;
	}

	public void setSupConPostal(String supConPostal) {
		this.supConPostal = supConPostal;
	}

	public String getSupConCountry() {
		return this.supConCountry;
	}

	public void setSupConCountry(String supConCountry) {
		this.supConCountry = supConCountry;
	}

	public String getSupConBusPhone() {
		return this.supConBusPhone;
	}

	public void setSupConBusPhone(String supConBusPhone) {
		this.supConBusPhone = supConBusPhone;
	}

	public String getSupConFax() {
		return this.supConFax;
	}

	public void setSupConFax(String supConFax) {
		this.supConFax = supConFax;
	}

	public String getSupConEmail() {
		return this.supConEmail;
	}

	public void setSupConEmail(String supConEmail) {
		this.supConEmail = supConEmail;
	}

	public String getSupConUrl() {
		return this.supConUrl;
	}

	public void setSupConUrl(String supConUrl) {
		this.supConUrl = supConUrl;
	}

	public String getAffiliationId() {
		return this.affiliationId;
	}

	public void setAffiliationId(String affiliationId) {
		this.affiliationId = affiliationId;
	}

	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

}
