package Models;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Packages generated by hbm2java
 */
public class Package implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer packageId;
	private String pkgName;
	private Date pkgStartDate;
	private Date pkgEndDate;
	private String pkgDesc;
	private Double pkgBasePrice;
	private Double pkgAgencyCommission;

	public Package() {
	}

	/**
	 * @param packageId
	 * @param pkgName
	 */
	public Package(Integer packageId, String pkgName) {
		super();
		this.packageId = packageId;
		this.pkgName = pkgName;
	}


	public Package(String pkgName, Double pkgBasePrice) {
		this.pkgName = pkgName;
		this.pkgBasePrice = pkgBasePrice;
	}

	public Package(Integer packageId, String pkgName, Date pkgStartDate, Date pkgEndDate, String pkgDesc, Double pkgBasePrice,
			Double pkgAgencyCommission) {
		this.packageId = packageId;
		this.pkgName = pkgName;
		this.pkgStartDate = pkgStartDate;
		this.pkgEndDate = pkgEndDate;
		this.pkgDesc = pkgDesc;
		this.pkgBasePrice = pkgBasePrice;
		this.pkgAgencyCommission = pkgAgencyCommission;
	}

	public Package(String pkgName, Date pkgStartDate, Date pkgEndDate, String pkgDesc, Double pkgBasePrice,
			Double pkgAgencyCommission) {
		super();
		this.pkgName = pkgName;
		this.pkgStartDate = pkgStartDate;
		this.pkgEndDate = pkgEndDate;
		this.pkgDesc = pkgDesc;
		this.pkgBasePrice = pkgBasePrice;
		this.pkgAgencyCommission = pkgAgencyCommission;
	}

	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	public String getPkgName() {
		return this.pkgName;
	}

	public void setPkgName(String pkgName) {
		this.pkgName = pkgName;
	}

	public Date getPkgStartDate() {
		return this.pkgStartDate;
	}

	public void setPkgStartDate(Date pkgStartDate) {
		this.pkgStartDate = pkgStartDate;
	}

	public Date getPkgEndDate() {
		return this.pkgEndDate;
	}

	public void setPkgEndDate(Date pkgEndDate) {
		this.pkgEndDate = pkgEndDate;
	}

	public String getPkgDesc() {
		return this.pkgDesc;
	}

	public void setPkgDesc(String pkgDesc) {
		this.pkgDesc = pkgDesc;
	}

	public Double getPkgBasePrice() {
		return this.pkgBasePrice;
	}

	public void setPkgBasePrice(Double pkgBasePrice) {
		this.pkgBasePrice = pkgBasePrice;
	}

	public Double getPkgAgencyCommission() {
		return this.pkgAgencyCommission;
	}

	public void setPkgAgencyCommission(Double pkgAgencyCommission) {
		this.pkgAgencyCommission = pkgAgencyCommission;
	}

	@Override
	public String toString() {
		return packageId + " "+ pkgName;
	}
	
	
	// Additional functions written by Kelsey Shorten
	public String getItemByTag(String tag) {

        // Formatters
        SimpleDateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        NumberFormat cf = NumberFormat.getCurrencyInstance();

        //price storage
        Double price = 1.0;
        Double tenpct = 0.9;
        Double fiftypct = 0.5;

        // Strings to return
        switch (tag) {
            case "packageId":
                return packageId.toString();
            case "pkgName":
                return pkgName;
            case "pkgDesc":
                return pkgDesc;
            case "pkgStartDate":
                return df.format(pkgStartDate);
            case "pkgEndDate":
                return df.format(pkgEndDate);
            case "totalPrice":
                price = getPkgPrice();
                return price.toString();
            case "discountTen":
                price = getPkgPrice();
                price = price * tenpct;
                return price.toString();
            case "discountFifty":
                price = getPkgPrice();
                price = price *(fiftypct);
                return price.toString();
            default:
                return packageId.toString();
        }


    }


    private Double  getPkgPrice() {
        return pkgBasePrice + pkgAgencyCommission;

    }
	

}
