package workshop6.travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * Affiliations generated by hbm2java
 */
public class Affiliations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String affilitationId;
	private String affName;
	private String affDesc;

	public Affiliations() {
	}

	public Affiliations(String affilitationId) {
		this.affilitationId = affilitationId;
	}

	public Affiliations(String affilitationId, String affName, String affDesc) {
		this.affilitationId = affilitationId;
		this.affName = affName;
		this.affDesc = affDesc;
	}

	public String getAffilitationId() {
		return this.affilitationId;
	}

	public void setAffilitationId(String affilitationId) {
		this.affilitationId = affilitationId;
	}

	public String getAffName() {
		return this.affName;
	}

	public void setAffName(String affName) {
		this.affName = affName;
	}

	public String getAffDesc() {
		return this.affDesc;
	}

	public void setAffDesc(String affDesc) {
		this.affDesc = affDesc;
	}

}
