package workshop6.travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Bookingdetails generated by hbm2java
 */
public class Bookingdetails implements java.io.Serializable {

	private Integer bookingDetailId;
	private Double itineraryNo;
	private Date tripStart;
	private Date tripEnd;
	private String description;
	private String destination;
	private BigDecimal basePrice;
	private BigDecimal agencyCommission;
	private Integer bookingId;
	private String regionId;
	private String classId;
	private String feeId;
	private Integer productSupplierId;

	public Bookingdetails() {
	}

	public Bookingdetails(Double itineraryNo, Date tripStart, Date tripEnd, String description, String destination,
			BigDecimal basePrice, BigDecimal agencyCommission, Integer bookingId, String regionId, String classId,
			String feeId, Integer productSupplierId) {
		this.itineraryNo = itineraryNo;
		this.tripStart = tripStart;
		this.tripEnd = tripEnd;
		this.description = description;
		this.destination = destination;
		this.basePrice = basePrice;
		this.agencyCommission = agencyCommission;
		this.bookingId = bookingId;
		this.regionId = regionId;
		this.classId = classId;
		this.feeId = feeId;
		this.productSupplierId = productSupplierId;
	}

	public Integer getBookingDetailId() {
		return this.bookingDetailId;
	}

	public void setBookingDetailId(Integer bookingDetailId) {
		this.bookingDetailId = bookingDetailId;
	}

	public Double getItineraryNo() {
		return this.itineraryNo;
	}

	public void setItineraryNo(Double itineraryNo) {
		this.itineraryNo = itineraryNo;
	}

	public Date getTripStart() {
		return this.tripStart;
	}

	public void setTripStart(Date tripStart) {
		this.tripStart = tripStart;
	}

	public Date getTripEnd() {
		return this.tripEnd;
	}

	public void setTripEnd(Date tripEnd) {
		this.tripEnd = tripEnd;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public BigDecimal getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(BigDecimal basePrice) {
		this.basePrice = basePrice;
	}

	public BigDecimal getAgencyCommission() {
		return this.agencyCommission;
	}

	public void setAgencyCommission(BigDecimal agencyCommission) {
		this.agencyCommission = agencyCommission;
	}

	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	public String getFeeId() {
		return this.feeId;
	}

	public void setFeeId(String feeId) {
		this.feeId = feeId;
	}

	public Integer getProductSupplierId() {
		return this.productSupplierId;
	}

	public void setProductSupplierId(Integer productSupplierId) {
		this.productSupplierId = productSupplierId;
	}

}
