package workshop6.travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * Creditcards generated by hbm2java
 */
public class Creditcards implements java.io.Serializable {

	private Integer creditCardId;
	private String ccname;
	private String ccnumber;
	private Date ccexpiry;
	private int customerId;

	public Creditcards() {
	}

	public Creditcards(String ccname, String ccnumber, Date ccexpiry, int customerId) {
		this.ccname = ccname;
		this.ccnumber = ccnumber;
		this.ccexpiry = ccexpiry;
		this.customerId = customerId;
	}

	public Integer getCreditCardId() {
		return this.creditCardId;
	}

	public void setCreditCardId(Integer creditCardId) {
		this.creditCardId = creditCardId;
	}

	public String getCcname() {
		return this.ccname;
	}

	public void setCcname(String ccname) {
		this.ccname = ccname;
	}

	public String getCcnumber() {
		return this.ccnumber;
	}

	public void setCcnumber(String ccnumber) {
		this.ccnumber = ccnumber;
	}

	public Date getCcexpiry() {
		return this.ccexpiry;
	}

	public void setCcexpiry(Date ccexpiry) {
		this.ccexpiry = ccexpiry;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

}
