package workshop6.travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * CustomersRewards generated by hbm2java
 */
public class CustomersRewards implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CustomersRewardsId id;
	private String rwdNumber;

	public CustomersRewards() {
	}

	public CustomersRewards(CustomersRewardsId id, String rwdNumber) {
		this.id = id;
		this.rwdNumber = rwdNumber;
	}

	public CustomersRewardsId getId() {
		return this.id;
	}

	public void setId(CustomersRewardsId id) {
		this.id = id;
	}

	public String getRwdNumber() {
		return this.rwdNumber;
	}

	public void setRwdNumber(String rwdNumber) {
		this.rwdNumber = rwdNumber;
	}

}
