package travelexperts;
// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * CustomersRewardsId generated by hbm2java
 */
public class CustomersRewardsId implements java.io.Serializable {

	private int customerId;
	private int rewardId;

	public CustomersRewardsId() {
	}

	public CustomersRewardsId(int customerId, int rewardId) {
		this.customerId = customerId;
		this.rewardId = rewardId;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public int getRewardId() {
		return this.rewardId;
	}

	public void setRewardId(int rewardId) {
		this.rewardId = rewardId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomersRewardsId))
			return false;
		CustomersRewardsId castOther = (CustomersRewardsId) other;

		return (this.getCustomerId() == castOther.getCustomerId()) && (this.getRewardId() == castOther.getRewardId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomerId();
		result = 37 * result + this.getRewardId();
		return result;
	}

}
