// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * EmployeesId generated by hbm2java
 */
public class EmployeesId implements java.io.Serializable {

	private String empFirstName;
	private String empMiddleInitial;
	private String empLastName;
	private String empBusPhone;
	private String empEmail;
	private String empPosition;

	public EmployeesId() {
	}

	public EmployeesId(String empFirstName, String empLastName, String empBusPhone, String empEmail,
			String empPosition) {
		this.empFirstName = empFirstName;
		this.empLastName = empLastName;
		this.empBusPhone = empBusPhone;
		this.empEmail = empEmail;
		this.empPosition = empPosition;
	}

	public EmployeesId(String empFirstName, String empMiddleInitial, String empLastName, String empBusPhone,
			String empEmail, String empPosition) {
		this.empFirstName = empFirstName;
		this.empMiddleInitial = empMiddleInitial;
		this.empLastName = empLastName;
		this.empBusPhone = empBusPhone;
		this.empEmail = empEmail;
		this.empPosition = empPosition;
	}

	public String getEmpFirstName() {
		return this.empFirstName;
	}

	public void setEmpFirstName(String empFirstName) {
		this.empFirstName = empFirstName;
	}

	public String getEmpMiddleInitial() {
		return this.empMiddleInitial;
	}

	public void setEmpMiddleInitial(String empMiddleInitial) {
		this.empMiddleInitial = empMiddleInitial;
	}

	public String getEmpLastName() {
		return this.empLastName;
	}

	public void setEmpLastName(String empLastName) {
		this.empLastName = empLastName;
	}

	public String getEmpBusPhone() {
		return this.empBusPhone;
	}

	public void setEmpBusPhone(String empBusPhone) {
		this.empBusPhone = empBusPhone;
	}

	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	public String getEmpPosition() {
		return this.empPosition;
	}

	public void setEmpPosition(String empPosition) {
		this.empPosition = empPosition;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeesId))
			return false;
		EmployeesId castOther = (EmployeesId) other;

		return ((this.getEmpFirstName() == castOther.getEmpFirstName()) || (this.getEmpFirstName() != null
				&& castOther.getEmpFirstName() != null && this.getEmpFirstName().equals(castOther.getEmpFirstName())))
				&& ((this.getEmpMiddleInitial() == castOther.getEmpMiddleInitial())
						|| (this.getEmpMiddleInitial() != null && castOther.getEmpMiddleInitial() != null
								&& this.getEmpMiddleInitial().equals(castOther.getEmpMiddleInitial())))
				&& ((this.getEmpLastName() == castOther.getEmpLastName())
						|| (this.getEmpLastName() != null && castOther.getEmpLastName() != null
								&& this.getEmpLastName().equals(castOther.getEmpLastName())))
				&& ((this.getEmpBusPhone() == castOther.getEmpBusPhone())
						|| (this.getEmpBusPhone() != null && castOther.getEmpBusPhone() != null
								&& this.getEmpBusPhone().equals(castOther.getEmpBusPhone())))
				&& ((this.getEmpEmail() == castOther.getEmpEmail()) || (this.getEmpEmail() != null
						&& castOther.getEmpEmail() != null && this.getEmpEmail().equals(castOther.getEmpEmail())))
				&& ((this.getEmpPosition() == castOther.getEmpPosition())
						|| (this.getEmpPosition() != null && castOther.getEmpPosition() != null
								&& this.getEmpPosition().equals(castOther.getEmpPosition())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmpFirstName() == null ? 0 : this.getEmpFirstName().hashCode());
		result = 37 * result + (getEmpMiddleInitial() == null ? 0 : this.getEmpMiddleInitial().hashCode());
		result = 37 * result + (getEmpLastName() == null ? 0 : this.getEmpLastName().hashCode());
		result = 37 * result + (getEmpBusPhone() == null ? 0 : this.getEmpBusPhone().hashCode());
		result = 37 * result + (getEmpEmail() == null ? 0 : this.getEmpEmail().hashCode());
		result = 37 * result + (getEmpPosition() == null ? 0 : this.getEmpPosition().hashCode());
		return result;
	}

}
