package workshop6.travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * PackagesProductsSuppliers generated by hbm2java
 */
public class PackagesProductsSuppliers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PackagesProductsSuppliersId id;

	public PackagesProductsSuppliers() {
	}

	public PackagesProductsSuppliers(PackagesProductsSuppliersId id) {
		this.id = id;
	}

	public PackagesProductsSuppliersId getId() {
		return this.id;
	}

	public void setId(PackagesProductsSuppliersId id) {
		this.id = id;
	}

}
