package travelexperts;

// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * Rewards generated by hbm2java
 */
public class Rewards implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rewardId;
	private String rwdName;
	private String rwdDesc;

	public Rewards() {
	}

	public Rewards(int rewardId) {
		this.rewardId = rewardId;
	}

	public Rewards(int rewardId, String rwdName, String rwdDesc) {
		this.rewardId = rewardId;
		this.rwdName = rwdName;
		this.rwdDesc = rwdDesc;
	}

	public int getRewardId() {
		return this.rewardId;
	}

	public void setRewardId(int rewardId) {
		this.rewardId = rewardId;
	}

	public String getRwdName() {
		return this.rwdName;
	}

	public void setRwdName(String rwdName) {
		this.rwdName = rwdName;
	}

	public String getRwdDesc() {
		return this.rwdDesc;
	}

	public void setRwdDesc(String rwdDesc) {
		this.rwdDesc = rwdDesc;
	}

}
