// default package
// Generated 29-Aug-2017 10:13:16 AM by Hibernate Tools 5.2.5.Final

/**
 * Triptypes generated by hbm2java
 */
public class Triptypes implements java.io.Serializable {

	private String tripTypeId;
	private String ttname;

	public Triptypes() {
	}

	public Triptypes(String tripTypeId) {
		this.tripTypeId = tripTypeId;
	}

	public Triptypes(String tripTypeId, String ttname) {
		this.tripTypeId = tripTypeId;
		this.ttname = ttname;
	}

	public String getTripTypeId() {
		return this.tripTypeId;
	}

	public void setTripTypeId(String tripTypeId) {
		this.tripTypeId = tripTypeId;
	}

	public String getTtname() {
		return this.ttname;
	}

	public void setTtname(String ttname) {
		this.ttname = ttname;
	}

}
