package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

import java.math.BigDecimal;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Optional;
import java.util.ResourceBundle;

import Models.DBConnection;
import Models.Package;
import Models.PackageDB;
import Models.Product;
import Models.ProductDB;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.MenuBar;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.util.converter.BigDecimalStringConverter;
import javafx.scene.control.Menu;

public class PackagesController implements Initializable{
	@FXML
	private MenuBar fxmenubar;
	@FXML
	private Menu fxDashboard;
	@FXML
	private Menu fxPackage;
	@FXML
	private Menu fxSupplier;
	@FXML
	private Menu fxProduct;
	@FXML
	private Menu fxBooking;
	@FXML
	private Menu fxCustomer;
	@FXML
	private Menu fxSendPromo;
	@FXML
	private ListView<Package> lvPackages;
	@FXML
	private TextField fxPackageId;
	@FXML
	private TextField fxPackageName;
	@FXML
	private TextField fxPkgDesc;
	@FXML
	private TextField fxPkgStartDate;
	@FXML
	private TextField fxPkgEndDate;
	@FXML
	private TextField fxPkgBasePrice;
	@FXML
	private TextField fxPkgAgencyCommission;
	@FXML
	private Button btnAdd;
	@FXML
	private Button btnEdit;
	@FXML
	private Button btnAddSave;
	@FXML
	private Button btnSaveEdit;
	@FXML
	private Button btnDelete;
	
	private Connection conn;
	private ObservableList<Package>data;

	// Event Listener on MenuItem.onAction
	@FXML
	public void openDashboard(ActionEvent event) {
		// TODO Autogenerated
		// close current window
    	Stage main = (Stage) fxmenubar.getScene().getWindow();
        main.close();
    	try {      
    		
	        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("Dashboard.fxml"));
            Parent dash = (Parent) fxmlLoader.load();
            Stage stage = new Stage();
            stage.setScene(new Scene(dash));  
            stage.show();
                               
        } catch(Exception e) {
           e.printStackTrace();
        }
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void openPackage(ActionEvent event) {
		// TODO Autogenerated
		Stage main = (Stage) fxmenubar.getScene().getWindow();
        main.close();
    	try {      
    		
	        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("Packages.fxml"));
            Parent pack = (Parent) fxmlLoader.load();
            Stage stage = new Stage();
            stage.setScene(new Scene(pack));  
            stage.show();
                               
        } catch(Exception e) {
           e.printStackTrace();
        }
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void openSupplier(ActionEvent event) {
		// TODO Autogenerated
		Stage main = (Stage) fxmenubar.getScene().getWindow();
        main.close();
    	try {      
    		
	        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("Suppliers.fxml"));
            Parent supp = (Parent) fxmlLoader.load();
            Stage stage = new Stage();
            stage.setScene(new Scene(supp));  
            stage.show();
                               
        } catch(Exception e) {
           e.printStackTrace();
        }
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void openProduct(ActionEvent event) {
		// TODO Autogenerated
		Stage main = (Stage) fxmenubar.getScene().getWindow();
        main.close();
    	try {      
    		
	        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("Products.fxml"));
            Parent prod = (Parent) fxmlLoader.load();
            Stage stage = new Stage();
            stage.setScene(new Scene(prod));  
            stage.show();
                               
        } catch(Exception e) {
           e.printStackTrace();
        }
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void openBooking(ActionEvent event) {
		// TODO Autogenerated
		Stage main = (Stage) fxmenubar.getScene().getWindow();
        main.close();
    	
    	try {      
    		
	        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("Bookings.fxml"));
            Parent book = (Parent) fxmlLoader.load();
            Stage stage = new Stage();
            stage.setScene(new Scene(book));  
            stage.show();
                               
        } catch(Exception e) {
           e.printStackTrace();
        }
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void openCustomer(ActionEvent event) {
		// TODO Autogenerated
		Stage main = (Stage) fxmenubar.getScene().getWindow();
        main.close();
        
    	try {      
    		
	        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("Customers.fxml"));
            Parent cust = (Parent) fxmlLoader.load();
            Stage stage = new Stage();
            stage.setScene(new Scene(cust));  
            stage.show();
                               
        } catch(Exception e) {
           e.printStackTrace();
        }
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void openSendPromo(ActionEvent event) {
		// TODO Autogenerated
		Stage main = (Stage) fxmenubar.getScene().getWindow();
        main.close();
		try {         		
		        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("SendPromotion.fxml"));
		        Parent promo = (Parent) fxmlLoader.load();
		        Stage stage = new Stage();
		        stage.setScene(new Scene(promo));  
		        stage.show();
	                               
	        } catch(Exception e) {
	           e.printStackTrace();
	        }
	}
	// Event Listener on ListView[#lvPackages].onMouseClicked
	@FXML
	public void selectPackage(MouseEvent event) {
		// TODO Autogenerated
		Package pkg = lvPackages.getSelectionModel().getSelectedItem();
		fxPackageId.setText(pkg.getPackageId() + "");
		fxPackageName.setText(pkg.getPkgName());
		fxPkgStartDate.setText(pkg.getPkgStartDate() + "");
		fxPkgEndDate.setText(pkg.getPkgEndDate() + "");
		fxPkgDesc.setText(pkg.getPkgDesc());
		fxPkgBasePrice.setText(pkg.getPkgBasePrice() + "");
		fxPkgAgencyCommission.setText(pkg.getPkgAgencyCommission() + "");
		
		fxPackageName.setEditable(false);
		btnEdit.setVisible(true);
		btnEdit.setDisable(false);
		btnAdd.setDisable(true);
		btnAdd.setVisible(true);
		btnAddSave.setVisible(false);
		btnSaveEdit.setVisible(false);
		btnDelete.setVisible(true);
		btnDelete.setDisable(false);
	}
	// Event Listener on Button[#btnAdd].onAction
	@FXML
	public void onAddPackage(ActionEvent event) {
		// TODO Autogenerated
		fxPackageId.setText("");
		fxPackageId.setDisable(true);
		
		fxPackageName.setText("");
		fxPackageName.setEditable(true);
		
		fxPkgStartDate.setText("");
		fxPkgStartDate.setEditable(true);
		
		fxPkgEndDate.setText("");
		fxPkgEndDate.setEditable(true);
		
		fxPkgDesc.setText("");
		fxPkgDesc.setEditable(true);
		
		fxPkgBasePrice.setText("");
		fxPkgBasePrice.setEditable(true);
		
		fxPkgAgencyCommission.setText("");
		fxPkgAgencyCommission.setEditable(true);
		
		btnAdd.setVisible(false);
		btnAddSave.setVisible(true);
		btnEdit.setDisable(true);
		btnDelete.setVisible(false);
	}
	// Event Listener on Button[#btnEdit].onAction
	@FXML
	public void onEditPackage(ActionEvent event) {
		// TODO Autogenerated
		btnEdit.setVisible(false);
		btnSaveEdit.setVisible(true);
		btnAdd.setVisible(false);
		btnDelete.setDisable(true);
		fxPackageId.setDisable(true);
		fxPackageName.setEditable(true);
		fxPkgStartDate.setEditable(true);
		fxPkgEndDate.setEditable(true);
		fxPkgDesc.setEditable(true);
		fxPkgBasePrice.setEditable(true);
		fxPkgAgencyCommission.setEditable(true);
	}
	// Event Listener on Button[#btnAddSave].onAction
	@FXML
	public void insertPackage(ActionEvent event) throws ParseException {
		// TODO Autogenerated
		
		DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
		
		String pkgName = fxPackageName.getText();
		Date pkgStartDate =  df.parse(fxPkgStartDate.getText());
		Date pkgEndDate = df.parse(fxPkgEndDate.getText());
		String pkgDesc = fxPkgDesc.getText();
		Double pkgBasePrice = Double.parseDouble(fxPkgBasePrice.getText());
		Double pkgAgencyCommission = Double.parseDouble(fxPkgAgencyCommission.getText());
		
		Package p = new Package();
		p.setPkgName(pkgName);
		p.setPkgStartDate(pkgStartDate);
		p.setPkgEndDate(pkgEndDate);
		p.setPkgDesc(pkgDesc);
		p.setPkgBasePrice(pkgBasePrice);
		p.setPkgAgencyCommission(pkgAgencyCommission);
		Boolean i = new PackageDB().addPackage(p);
		if(i) {
			System.out.println("Sucessfully Added");
			
		} else {
			System.out.println("Failed");
		}
		loadPackageList();
		clearControls();
	}

	// Event Listener on Button[#btnSaveEdit].onAction
	@FXML
	public void updatePackage(ActionEvent event) throws ParseException {
		// TODO Autogenerated
		DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
		String pkgName = fxPackageName.getText();
		Date pkgStartDate =  df.parse(fxPkgStartDate.getText());
		Date pkgEndDate = df.parse(fxPkgEndDate.getText());
		String pkgDesc = fxPkgDesc.getText();
		Double pkgBasePrice = Double.parseDouble(fxPkgBasePrice.getText());
		Double pkgAgencyCommission = Double.parseDouble(fxPkgAgencyCommission.getText());
		
		Integer PackageId = lvPackages.getSelectionModel().getSelectedItem().getPackageId();
		Package p = new Package();
		p.setPackageId(PackageId);
		p.setPkgName(pkgName);
		p.setPkgStartDate(pkgStartDate);
		p.setPkgEndDate(pkgEndDate);
		p.setPkgDesc(pkgDesc);
		p.setPkgBasePrice(pkgBasePrice);
		p.setPkgAgencyCommission(pkgAgencyCommission);
		
		Boolean i = new PackageDB().updatePackage(p);
		if(i) {
			System.out.println("Sucessfully Updated");
			
		} else {
			System.out.println("Failed");
		}
		loadPackageList();
		clearControls();
		
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void deletePackage(ActionEvent event) throws ParseException {
		// TODO Autogenerated
		DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
		String pkgName = fxPackageName.getText();
		Date pkgStartDate =  df.parse(fxPkgStartDate.getText());
		Date pkgEndDate = df.parse(fxPkgEndDate.getText());
		String pkgDesc = fxPkgDesc.getText();
		Double pkgBasePrice = Double.parseDouble(fxPkgBasePrice.getText());
		Double pkgAgencyCommission = Double.parseDouble(fxPkgAgencyCommission.getText());
		Integer PackageId = lvPackages.getSelectionModel().getSelectedItem().getPackageId();
		
		Package p = new Package();
		p.setPackageId(PackageId);
		p.setPkgName(pkgName);
		p.setPkgStartDate(pkgStartDate);
		p.setPkgEndDate(pkgEndDate);
		p.setPkgDesc(pkgDesc);
		p.setPkgBasePrice(pkgBasePrice);
		p.setPkgAgencyCommission(pkgAgencyCommission);
		
		
		Alert alert = new Alert(AlertType.CONFIRMATION);
		alert.setTitle("Delete Package Confirmation!");
		alert.setHeaderText("Delete Package '" + pkgName +"'");
		alert.setContentText("Are you sure, you want delete this package?");

		Optional<ButtonType> result = alert.showAndWait();
		
		if (result.get() == ButtonType.OK){
			Boolean i = new PackageDB().deletePackage(p);
			if(i) {
				System.out.println("Sucessfully Deleted");
				
			} else {
				System.out.println("Failed");
			}
			loadPackageList();
			clearControls();
		} 
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		btnAddSave.setVisible(false);
		btnDelete.setVisible(false);
		btnEdit.setDisable(true);
		btnSaveEdit.setVisible(false);
		try {
			conn = new DBConnection().getConnection();
			loadPackageList();
		} catch (SQLException | ClassNotFoundException e) {
			
			e.printStackTrace();
		}
	}
	
	private void clearControls() {
		// TODO Auto-generated method stub
		fxPackageName.setText("");
		fxPackageId.setText("");
		fxPkgStartDate.setText("");
		fxPkgEndDate.setText("");
		fxPkgDesc.setText("");
		fxPkgBasePrice.setText("");
		fxPkgAgencyCommission.setText("");
		btnAdd.setDisable(false);
		btnAdd.setVisible(true);
		btnAddSave.setVisible(false);
		btnSaveEdit.setVisible(false);
		btnEdit.setVisible(true);
		btnEdit.setDisable(true);	
		btnDelete.setVisible(false);		
	}
	private void loadPackageList() {
		// TODO Auto-generated method stub
		data = FXCollections.observableArrayList();
		new PackageDB();
		ArrayList<Package> rs = PackageDB.getPackages();

		for( Package pkg: rs) {
			data.add(new Package(pkg.getPackageId(), 
					pkg.getPkgName(), pkg.getPkgStartDate(),
					pkg.getPkgEndDate(), pkg.getPkgDesc(), 
					pkg.getPkgBasePrice(), pkg.getPkgAgencyCommission()));
		}
		
		lvPackages.setItems(data);	
	}
}
